package utils;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;


public final class EnvironmentWriter {

    
    public static final String RESULTS_DIR = "target/allure-results";

    
    public static final String SELENIUM_VERSION = "4.48.0";
    public static final String ASPECTJ_VERSION = "1.9.21";

    private static final AtomicBoolean WRITTEN = new AtomicBoolean(false);
    private static final Object LOCK = new Object();

    private EnvironmentWriter() {
    }

    
    public static void writeAll() {
        if (!WRITTEN.compareAndSet(false, true)) {
            return;
        }
        synchronized (LOCK) {
            try {
                Path resultsDir = Paths.get(RESULTS_DIR);
                Files.createDirectories(resultsDir);
                writeAtomically(resultsDir.resolve("environment.properties"),
                        buildEnvironmentProperties().getBytes(StandardCharsets.UTF_8));
                writeAtomically(resultsDir.resolve("categories.json"),
                        CATEGORIES_JSON.getBytes(StandardCharsets.UTF_8));
            } catch (IOException e) {
                throw new IllegalStateException("Не удалось записать служебные файлы Allure", e);
            }
        }
    }

    
    public static String buildEnvironmentProperties() {
        Map<String, String> values = new LinkedHashMap<>();
        values.put("os.name", System.getProperty("os.name"));
        values.put("os.version", System.getProperty("os.version"));
        values.put("os.arch", System.getProperty("os.arch"));
        values.put("jdk.version", System.getProperty("java.version"));
        values.put("jdk.vendor", System.getProperty("java.vendor"));
        values.put("build.tool", "Maven 3.9.16, maven-surefire-plugin 3.2.5");
        values.put("selenium.version", SELENIUM_VERSION);
        values.put("testng.version", libraryVersionOr("org.testng.TestNG", "7.10.2"));
        values.put("allure.version", libraryVersionOr("io.qameta.allure.Allure", "2.25.0"));
        values.put("aspectj.version", ASPECTJ_VERSION);
        values.put("driver.manager", "SeleniumManager (built into Selenium " + SELENIUM_VERSION
                + "; WebDriverManager is not required)");
        values.put("browser", "Chrome / Firefox / Edge");
        values.put("browser.installed.versions", "Chrome 154.0.8037.98; Firefox 157.0.1; Edge 154.0.4258.62");
        values.put("base.url", TestConfig.BASE_URL);
        values.put("wait.explicit.seconds", String.valueOf(TestConfig.EXPLICIT_WAIT_SECONDS));
        values.put("retry.count", System.getProperty("retry.count", "3"));
        values.put("suite", "testng-crossbrowser.xml: parallel=tests, thread-count=2");

        StringBuilder builder = new StringBuilder();
        builder.append("# Test run environment (generated by utils.EnvironmentWriter)")
                .append(System.lineSeparator());
        values.forEach((key, value) -> builder.append(key).append('=')
                .append(value == null ? "" : value).append(System.lineSeparator()));
        return builder.toString();
    }

    
    public static String libraryVersionOr(String className, String fallback) {
        String version = libraryVersion(className);
        return "unknown".equals(version) ? fallback : version;
    }

    
    public static String libraryVersion(String className) {
        try {
            Class<?> type = Class.forName(className);
            String version = type.getPackage() == null ? null : type.getPackage().getImplementationVersion();
            return version == null || version.isBlank() ? "unknown" : version;
        } catch (Throwable e) {
            return "unknown";
        }
    }

    private static void writeAtomically(Path target, byte[] content) throws IOException {
        Path temp = target.resolveSibling(target.getFileName() + "." + UUID.randomUUID() + ".tmp");
        try (OutputStream out = Files.newOutputStream(temp)) {
            out.write(content);
        }
        try {
            Files.move(temp, target, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
        } catch (IOException e) {
            Files.move(temp, target, StandardCopyOption.REPLACE_EXISTING);
        }
    }

    
    public static final String CATEGORIES_JSON = """
            [
              {
                "name": "Падения проверок (AssertionError)",
                "matchedStatuses": ["failed"],
                "messageRegex": ".*(AssertionError|Ожидал|expected).*"
              },
              {
                "name": "Элемент не найден (NoSuchElementException)",
                "matchedStatuses": ["broken", "failed"],
                "traceRegex": ".*NoSuchElementException.*"
              },
              {
                "name": "Превышено ожидание (TimeoutException)",
                "matchedStatuses": ["broken", "failed"],
                "traceRegex": ".*(TimeoutException|Expected condition failed).*"
              },
              {
                "name": "Проблемы с драйвером/браузером (WebDriverException)",
                "matchedStatuses": ["broken"],
                "traceRegex": ".*(WebDriverException|SessionNotCreatedException|NoSuchSessionException).*"
              },
              {
                "name": "Нестабильные элементы (Stale/Intercepted)",
                "matchedStatuses": ["broken", "failed"],
                "traceRegex": ".*(StaleElementReferenceException|ElementClickInterceptedException).*"
              },
              {
                "name": "Пропущенные тесты",
                "matchedStatuses": ["skipped"]
              }
            ]
            """;
}
